version: "3.9"
services:
  #NGINX
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro
      - ./logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80 #http
      - 443:443 #https
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
