version: "3.9"
services:
  #APP
  sendpro_app:
    image: php:8.2.7-fpm-bullseye
    container_name: sendpro_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.7-fpm-bullseye'
    volumes:
      - ./app:/var/www/sendpro.com.br
  #MYSQL
  sendpro_db:
    image: ${DB_IMAGE_SENDPRO}
    container_name: ${DB_CONTAINER_NAME_SENDPRO}
    restart: always
    ports:
      - ${DB_PORT_SENDPRO}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_SENDPRO}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT_SENDPRO}
      MYSQL_PASSWORD: ${DB_PASSWORD_SENDPRO}
      MYSQL_USER: ${DB_USERNAME_SENDPRO}
    volumes:
      - ./mysql-data:/var/lib/mysql
  #REDIS
  sendpro_redis:
    image: ${REDIS_IMAGE_SENDPRO}
    container_name: ${REDIS_CONTAINER_NAME_SENDPRO}
    command: redis-server --save 20 1 --loglevel warning --appendonly yes --replica-read-only no --requirepass ${REDIS_PASSWORD_SENDPRO}
    volumes:
        - ./redis/data:/data
    restart: always
    ports:
      - ${REDIS_PORT_SENDPRO}:6379
